// **********************************************************************
// This file was generated by a KANT parser!
// KANT version KANT_VERSION.
// **********************************************************************

#ifndef __LOGF_H_
#define __LOGF_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Kant.h"
#include "tup/KantJson.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace kant
{
    struct LogInfo : public kant::KantStructBase
    {
    public:
        static string className()
        {
            return "kant.LogInfo";
        }
        static string MD5()
        {
            return "52a804c9ac9b5171414e399739cb6079";
        }
        LogInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            appname = "";
            servername = "";
            sFilename = "";
            sFormat = "";
            setdivision = "";
            bHasSufix = true;
            bHasAppNamePrefix = true;
            bHasSquareBracket = false;
            sConcatStr = "_";
            sSepar = "|";
            sLogType = "";
        }
        template<typename WriterT>
        void writeTo(kant::KantOutputStream<WriterT>& _os) const
        {
            _os.write(appname, 0);
            _os.write(servername, 1);
            _os.write(sFilename, 2);
            _os.write(sFormat, 3);
            if (setdivision != "")
            {
                _os.write(setdivision, 4);
            }
            if (bHasSufix != true)
            {
                _os.write(bHasSufix, 5);
            }
            if (bHasAppNamePrefix != true)
            {
                _os.write(bHasAppNamePrefix, 6);
            }
            if (bHasSquareBracket != false)
            {
                _os.write(bHasSquareBracket, 7);
            }
            if (sConcatStr != "_")
            {
                _os.write(sConcatStr, 8);
            }
            if (sSepar != "|")
            {
                _os.write(sSepar, 9);
            }
            if (sLogType != "")
            {
                _os.write(sLogType, 10);
            }
        }
        template<typename ReaderT>
        void readFrom(kant::KantInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(appname, 0, true);
            _is.read(servername, 1, true);
            _is.read(sFilename, 2, true);
            _is.read(sFormat, 3, true);
            _is.read(setdivision, 4, false);
            _is.read(bHasSufix, 5, false);
            _is.read(bHasAppNamePrefix, 6, false);
            _is.read(bHasSquareBracket, 7, false);
            _is.read(sConcatStr, 8, false);
            _is.read(sSepar, 9, false);
            _is.read(sLogType, 10, false);
        }
        kant::JsonValueObjPtr writeToJson() const
        {
            kant::JsonValueObjPtr p = std::make_shared<kant::JsonValueObj>();
            p->value["appname"] = kant::JsonOutput::writeJson(appname);
            p->value["servername"] = kant::JsonOutput::writeJson(servername);
            p->value["sFilename"] = kant::JsonOutput::writeJson(sFilename);
            p->value["sFormat"] = kant::JsonOutput::writeJson(sFormat);
            p->value["setdivision"] = kant::JsonOutput::writeJson(setdivision);
            p->value["bHasSufix"] = kant::JsonOutput::writeJson(bHasSufix);
            p->value["bHasAppNamePrefix"] = kant::JsonOutput::writeJson(bHasAppNamePrefix);
            p->value["bHasSquareBracket"] = kant::JsonOutput::writeJson(bHasSquareBracket);
            p->value["sConcatStr"] = kant::JsonOutput::writeJson(sConcatStr);
            p->value["sSepar"] = kant::JsonOutput::writeJson(sSepar);
            p->value["sLogType"] = kant::JsonOutput::writeJson(sLogType);
            return p;
        }
        string writeToJsonString() const
        {
            return kant::KT_Json::writeValue(writeToJson());
        }
        void readFromJson(const kant::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != kant::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw kant::KT_Json_Exception(s);
            }
            kant::JsonValueObjPtr pObj=std::dynamic_pointer_cast<kant::JsonValueObj>(p);
            kant::JsonInput::readJson(appname,pObj->value["appname"], true);
            kant::JsonInput::readJson(servername,pObj->value["servername"], true);
            kant::JsonInput::readJson(sFilename,pObj->value["sFilename"], true);
            kant::JsonInput::readJson(sFormat,pObj->value["sFormat"], true);
            kant::JsonInput::readJson(setdivision,pObj->value["setdivision"], false);
            kant::JsonInput::readJson(bHasSufix,pObj->value["bHasSufix"], false);
            kant::JsonInput::readJson(bHasAppNamePrefix,pObj->value["bHasAppNamePrefix"], false);
            kant::JsonInput::readJson(bHasSquareBracket,pObj->value["bHasSquareBracket"], false);
            kant::JsonInput::readJson(sConcatStr,pObj->value["sConcatStr"], false);
            kant::JsonInput::readJson(sSepar,pObj->value["sSepar"], false);
            kant::JsonInput::readJson(sLogType,pObj->value["sLogType"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(kant::KT_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            kant::KantDisplayer _ds(_os, _level);
            _ds.display(appname,"appname");
            _ds.display(servername,"servername");
            _ds.display(sFilename,"sFilename");
            _ds.display(sFormat,"sFormat");
            _ds.display(setdivision,"setdivision");
            _ds.display(bHasSufix,"bHasSufix");
            _ds.display(bHasAppNamePrefix,"bHasAppNamePrefix");
            _ds.display(bHasSquareBracket,"bHasSquareBracket");
            _ds.display(sConcatStr,"sConcatStr");
            _ds.display(sSepar,"sSepar");
            _ds.display(sLogType,"sLogType");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            kant::KantDisplayer _ds(_os, _level);
            _ds.displaySimple(appname, true);
            _ds.displaySimple(servername, true);
            _ds.displaySimple(sFilename, true);
            _ds.displaySimple(sFormat, true);
            _ds.displaySimple(setdivision, true);
            _ds.displaySimple(bHasSufix, true);
            _ds.displaySimple(bHasAppNamePrefix, true);
            _ds.displaySimple(bHasSquareBracket, true);
            _ds.displaySimple(sConcatStr, true);
            _ds.displaySimple(sSepar, true);
            _ds.displaySimple(sLogType, false);
            return _os;
        }
    public:
        std::string appname;
        std::string servername;
        std::string sFilename;
        std::string sFormat;
        std::string setdivision;
        kant::Bool bHasSufix;
        kant::Bool bHasAppNamePrefix;
        kant::Bool bHasSquareBracket;
        std::string sConcatStr;
        std::string sSepar;
        std::string sLogType;
    };
    inline bool operator==(const LogInfo&l, const LogInfo&r)
    {
        return l.appname == r.appname && l.servername == r.servername && l.sFilename == r.sFilename && l.sFormat == r.sFormat && l.setdivision == r.setdivision && l.bHasSufix == r.bHasSufix && l.bHasAppNamePrefix == r.bHasAppNamePrefix && l.bHasSquareBracket == r.bHasSquareBracket && l.sConcatStr == r.sConcatStr && l.sSepar == r.sSepar && l.sLogType == r.sLogType;
    }
    inline bool operator!=(const LogInfo&l, const LogInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const LogInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,LogInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


    /* callback of async proxy for client */
    class LogPrxCallback: public kant::ServantProxyCallback
    {
    public:
        virtual ~LogPrxCallback(){}
        virtual void callback_logger()
        { throw std::runtime_error("callback_logger() override incorrect."); }
        virtual void callback_logger_exception(kant::Int32 ret)
        { throw std::runtime_error("callback_logger_exception() override incorrect."); }

        virtual void callback_loggerbyInfo()
        { throw std::runtime_error("callback_loggerbyInfo() override incorrect."); }
        virtual void callback_loggerbyInfo_exception(kant::Int32 ret)
        { throw std::runtime_error("callback_loggerbyInfo_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw KT_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(kant::ReqMessagePtr msg)
        {
            static ::std::string __Log_all[]=
            {
                "logger",
                "loggerbyInfo"
            };
            pair<string*, string*> r = equal_range(__Log_all, __Log_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return kant::KANTSERVERNOFUNCERR;
            switch(r.first - __Log_all)
            {
                case 0:
                {
                    if (msg->response->iRet != kant::KANTSERVERSUCCESS)
                    {
                        callback_logger_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    kant::KantInputStream<kant::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_logger();

                    pCbtd->delResponseContext();

                    return kant::KANTSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != kant::KANTSERVERSUCCESS)
                    {
                        callback_loggerbyInfo_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    kant::KantInputStream<kant::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_loggerbyInfo();

                    pCbtd->delResponseContext();

                    return kant::KANTSERVERSUCCESS;

                }
            }
            return kant::KANTSERVERNOFUNCERR;
        }

    };
    typedef std::shared_ptr<LogPrxCallback> LogPrxCallbackPtr;

    //callback of promise async proxy for client
    class LogPrxCallbackPromise: public kant::ServantProxyCallback
    {
    public:
        virtual ~LogPrxCallbackPromise(){}
    public:
        struct Promiselogger
        {
        public:
            map<std::string, std::string> _mRspContext;
        };
        
        typedef std::shared_ptr< LogPrxCallbackPromise::Promiselogger > PromiseloggerPtr;

        LogPrxCallbackPromise(const kant::Promise< LogPrxCallbackPromise::PromiseloggerPtr > &promise)
        : _promise_logger(promise)
        {}
        
        virtual void callback_logger(const LogPrxCallbackPromise::PromiseloggerPtr &ptr)
        {
            _promise_logger.setValue(ptr);
        }
        virtual void callback_logger_exception(kant::Int32 ret)
        {
            std::string str("");
            str += "Function:logger_exception|Ret:";
            str += KT_Common::tostr(ret);
            _promise_logger.setException(kant::copyException(str, ret));
        }

    protected:
        kant::Promise< LogPrxCallbackPromise::PromiseloggerPtr > _promise_logger;

    public:
        struct PromiseloggerbyInfo
        {
        public:
            map<std::string, std::string> _mRspContext;
        };
        
        typedef std::shared_ptr< LogPrxCallbackPromise::PromiseloggerbyInfo > PromiseloggerbyInfoPtr;

        LogPrxCallbackPromise(const kant::Promise< LogPrxCallbackPromise::PromiseloggerbyInfoPtr > &promise)
        : _promise_loggerbyInfo(promise)
        {}
        
        virtual void callback_loggerbyInfo(const LogPrxCallbackPromise::PromiseloggerbyInfoPtr &ptr)
        {
            _promise_loggerbyInfo.setValue(ptr);
        }
        virtual void callback_loggerbyInfo_exception(kant::Int32 ret)
        {
            std::string str("");
            str += "Function:loggerbyInfo_exception|Ret:";
            str += KT_Common::tostr(ret);
            _promise_loggerbyInfo.setException(kant::copyException(str, ret));
        }

    protected:
        kant::Promise< LogPrxCallbackPromise::PromiseloggerbyInfoPtr > _promise_loggerbyInfo;

    public:
        virtual int onDispatch(kant::ReqMessagePtr msg)
        {
            static ::std::string __Log_all[]=
            {
                "logger",
                "loggerbyInfo"
            };

            pair<string*, string*> r = equal_range(__Log_all, __Log_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return kant::KANTSERVERNOFUNCERR;
            switch(r.first - __Log_all)
            {
                case 0:
                {
                    if (msg->response->iRet != kant::KANTSERVERSUCCESS)
                    {
                        callback_logger_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    kant::KantInputStream<kant::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    LogPrxCallbackPromise::PromiseloggerPtr ptr = std::make_shared<LogPrxCallbackPromise::Promiselogger>();

                    try
                    {
                    }
                    catch(std::exception &ex)
                    {
                        callback_logger_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_logger_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_logger(ptr);

                    return kant::KANTSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != kant::KANTSERVERSUCCESS)
                    {
                        callback_loggerbyInfo_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    kant::KantInputStream<kant::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);

                    LogPrxCallbackPromise::PromiseloggerbyInfoPtr ptr = std::make_shared<LogPrxCallbackPromise::PromiseloggerbyInfo>();

                    try
                    {
                    }
                    catch(std::exception &ex)
                    {
                        callback_loggerbyInfo_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loggerbyInfo_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response->context;

                    callback_loggerbyInfo(ptr);

                    return kant::KANTSERVERSUCCESS;

                }
            }
            return kant::KANTSERVERNOFUNCERR;
        }

    };
    typedef std::shared_ptr<LogPrxCallbackPromise> LogPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class LogCoroPrxCallback: public LogPrxCallback
    {
    public:
        virtual ~LogCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(kant::ReqMessagePtr msg)
        {
            static ::std::string __Log_all[]=
            {
                "logger",
                "loggerbyInfo"
            };

            pair<string*, string*> r = equal_range(__Log_all, __Log_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return kant::KANTSERVERNOFUNCERR;
            switch(r.first - __Log_all)
            {
                case 0:
                {
                    if (msg->response->iRet != kant::KANTSERVERSUCCESS)
                    {
                        callback_logger_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    kant::KantInputStream<kant::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        setResponseContext(msg->response->context);

                        callback_logger();

                    }
                    catch(std::exception &ex)
                    {
                        callback_logger_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_logger_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }

                    return kant::KANTSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response->iRet != kant::KANTSERVERSUCCESS)
                    {
                        callback_loggerbyInfo_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    kant::KantInputStream<kant::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        setResponseContext(msg->response->context);

                        callback_loggerbyInfo();

                    }
                    catch(std::exception &ex)
                    {
                        callback_loggerbyInfo_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loggerbyInfo_exception(kant::KANTCLIENTDECODEERR);

                        return kant::KANTCLIENTDECODEERR;
                    }

                    return kant::KANTSERVERSUCCESS;

                }
            }
            return kant::KANTSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef std::shared_ptr<LogCoroPrxCallback> LogCoroPrxCallbackPtr;

    /* proxy for client */
    class LogProxy : public kant::ServantProxy
    {
    public:
        typedef map<string, string> KANT_CONTEXT;
        LogProxy(Communicator* pCommunicator, const string& name, const string& setName)
                : ServantProxy(pCommunicator, name, setName) {}

        void logger(const std::string & app,const std::string & server,const std::string & file,const std::string & format,const vector<std::string> & buffer,const map<string, string> &context = KANT_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(file, 3);
            _os.write(format, 4);
            _os.write(buffer, 5);
            std::map<string, string> _mStatus;
            shared_ptr<kant::ResponsePacket> rep = kant_invoke(kant::KANTNORMAL,"logger", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            kant::KantInputStream<kant::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
        }

        void async_logger(LogPrxCallbackPtr callback,const std::string &app,const std::string &server,const std::string &file,const std::string &format,const vector<std::string> &buffer,const map<string, string>& context = KANT_CONTEXT())
        {
            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(file, 3);
            _os.write(format, 4);
            _os.write(buffer, 5);
            std::map<string, string> _mStatus;
            kant_invoke_async(kant::KANTNORMAL,"logger", _os, context, _mStatus, callback);
        }
        
        kant::Future< LogPrxCallbackPromise::PromiseloggerPtr > promise_async_logger(const std::string &app,const std::string &server,const std::string &file,const std::string &format,const vector<std::string> &buffer,const map<string, string>& context)
        {
            kant::Promise< LogPrxCallbackPromise::PromiseloggerPtr > promise;
            LogPrxCallbackPromisePtr callback = std::make_shared<LogPrxCallbackPromise>(promise);

            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(file, 3);
            _os.write(format, 4);
            _os.write(buffer, 5);
            std::map<string, string> _mStatus;
            kant_invoke_async(kant::KANTNORMAL,"logger", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_logger(LogCoroPrxCallbackPtr callback,const std::string &app,const std::string &server,const std::string &file,const std::string &format,const vector<std::string> &buffer,const map<string, string>& context = KANT_CONTEXT())
        {
            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(file, 3);
            _os.write(format, 4);
            _os.write(buffer, 5);
            std::map<string, string> _mStatus;
            kant_invoke_async(kant::KANTNORMAL,"logger", _os, context, _mStatus, callback, true);
        }

        void loggerbyInfo(const kant::LogInfo & info,const vector<std::string> & buffer,const map<string, string> &context = KANT_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(info, 1);
            _os.write(buffer, 2);
            std::map<string, string> _mStatus;
            shared_ptr<kant::ResponsePacket> rep = kant_invoke(kant::KANTNORMAL,"loggerbyInfo", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            kant::KantInputStream<kant::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
        }

        void async_loggerbyInfo(LogPrxCallbackPtr callback,const kant::LogInfo &info,const vector<std::string> &buffer,const map<string, string>& context = KANT_CONTEXT())
        {
            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(info, 1);
            _os.write(buffer, 2);
            std::map<string, string> _mStatus;
            kant_invoke_async(kant::KANTNORMAL,"loggerbyInfo", _os, context, _mStatus, callback);
        }
        
        kant::Future< LogPrxCallbackPromise::PromiseloggerbyInfoPtr > promise_async_loggerbyInfo(const kant::LogInfo &info,const vector<std::string> &buffer,const map<string, string>& context)
        {
            kant::Promise< LogPrxCallbackPromise::PromiseloggerbyInfoPtr > promise;
            LogPrxCallbackPromisePtr callback = std::make_shared<LogPrxCallbackPromise>(promise);

            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(info, 1);
            _os.write(buffer, 2);
            std::map<string, string> _mStatus;
            kant_invoke_async(kant::KANTNORMAL,"loggerbyInfo", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_loggerbyInfo(LogCoroPrxCallbackPtr callback,const kant::LogInfo &info,const vector<std::string> &buffer,const map<string, string>& context = KANT_CONTEXT())
        {
            kant::KantOutputStream<kant::BufferWriterVector> _os;
            _os.write(info, 1);
            _os.write(buffer, 2);
            std::map<string, string> _mStatus;
            kant_invoke_async(kant::KANTNORMAL,"loggerbyInfo", _os, context, _mStatus, callback, true);
        }

        LogProxy* kant_hash(int64_t key)
        {
            return (LogProxy*)ServantProxy::kant_hash(key);
        }

        LogProxy* kant_consistent_hash(int64_t key)
        {
            return (LogProxy*)ServantProxy::kant_consistent_hash(key);
        }

        LogProxy* kant_open_trace(bool traceParam = false)
        {
            return (LogProxy*)ServantProxy::kant_open_trace(traceParam);
        }

        LogProxy* kant_set_timeout(int msecond)
        {
            return (LogProxy*)ServantProxy::kant_set_timeout(msecond);
        }

        static const char* kant_prxname() { return "LogProxy"; }
    };
    typedef std::shared_ptr<LogProxy> LogPrx;

    /* servant for server */
    class Log : public kant::Servant
    {
    public:
        virtual ~Log(){}
        virtual void logger(const std::string & app,const std::string & server,const std::string & file,const std::string & format,const vector<std::string> & buffer,kant::KantCurrentPtr current) = 0;
        static void async_response_logger(kant::KantCurrentPtr current)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<kant::BufferWriterVector, kant::BufferReader>  kantAttr;
                kantAttr.setVersion(current->getRequestVersion());

                vector<char> sTupResponseBuffer;
                kantAttr.encode(sTupResponseBuffer);
                current->sendResponse(kant::KANTSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                kant::JsonValueObjPtr _p = std::make_shared< kant::JsonValueObj>();
                vector<char> sJsonResponseBuffer;
                kant::KT_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(kant::KANTSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                kant::KantOutputStream<kant::BufferWriterVector> _os;
                current->sendResponse(kant::KANTSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual void loggerbyInfo(const kant::LogInfo & info,const vector<std::string> & buffer,kant::KantCurrentPtr current) = 0;
        static void async_response_loggerbyInfo(kant::KantCurrentPtr current)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<kant::BufferWriterVector, kant::BufferReader>  kantAttr;
                kantAttr.setVersion(current->getRequestVersion());

                vector<char> sTupResponseBuffer;
                kantAttr.encode(sTupResponseBuffer);
                current->sendResponse(kant::KANTSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                kant::JsonValueObjPtr _p = std::make_shared< kant::JsonValueObj>();
                vector<char> sJsonResponseBuffer;
                kant::KT_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(kant::KANTSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                kant::KantOutputStream<kant::BufferWriterVector> _os;
                current->sendResponse(kant::KANTSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(kant::KantCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __kant__Log_all[]=
            {
                "logger",
                "loggerbyInfo"
            };

            pair<string*, string*> r = equal_range(__kant__Log_all, __kant__Log_all+2, _current->getFuncName());
            if(r.first == r.second) return kant::KANTSERVERNOFUNCERR;
            switch(r.first - __kant__Log_all)
            {
                case 0:
                {
                    kant::KantInputStream<kant::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string server;
                    std::string file;
                    std::string format;
                    vector<std::string> buffer;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<kant::BufferWriterVector, kant::BufferReader>  kantAttr;
                        kantAttr.setVersion(_current->getRequestVersion());
                        kantAttr.decode(_current->getRequestBuffer());
                        kantAttr.get("app", app);
                        kantAttr.get("server", server);
                        kantAttr.get("file", file);
                        kantAttr.get("format", format);
                        kantAttr.get("buffer", buffer);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        kant::JsonValueObjPtr _jsonPtr = std::dynamic_pointer_cast<kant::JsonValueObj>(kant::KT_Json::getValue(_current->getRequestBuffer()));
                        kant::JsonInput::readJson(app, _jsonPtr->value["app"], true);
                        kant::JsonInput::readJson(server, _jsonPtr->value["server"], true);
                        kant::JsonInput::readJson(file, _jsonPtr->value["file"], true);
                        kant::JsonInput::readJson(format, _jsonPtr->value["format"], true);
                        kant::JsonInput::readJson(buffer, _jsonPtr->value["buffer"], true);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(server, 2, true);
                        _is.read(file, 3, true);
                        _is.read(format, 4, true);
                        _is.read(buffer, 5, true);
                    }
                    logger(app,server,file,format,buffer, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<kant::BufferWriterVector, kant::BufferReader>  kantAttr;
                            kantAttr.setVersion(_current->getRequestVersion());
                            kantAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            kant::JsonValueObjPtr _p = std::make_shared< kant::JsonValueObj>();
                            kant::KT_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            kant::KantOutputStream<kant::BufferWriterVector> _os;
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return kant::KANTSERVERSUCCESS;

                }
                case 1:
                {
                    kant::KantInputStream<kant::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    kant::LogInfo info;
                    vector<std::string> buffer;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<kant::BufferWriterVector, kant::BufferReader>  kantAttr;
                        kantAttr.setVersion(_current->getRequestVersion());
                        kantAttr.decode(_current->getRequestBuffer());
                        kantAttr.get("info", info);
                        kantAttr.get("buffer", buffer);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        kant::JsonValueObjPtr _jsonPtr = std::dynamic_pointer_cast<kant::JsonValueObj>(kant::KT_Json::getValue(_current->getRequestBuffer()));
                        kant::JsonInput::readJson(info, _jsonPtr->value["info"], true);
                        kant::JsonInput::readJson(buffer, _jsonPtr->value["buffer"], true);
                    }
                    else
                    {
                        _is.read(info, 1, true);
                        _is.read(buffer, 2, true);
                    }
                    loggerbyInfo(info,buffer, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<kant::BufferWriterVector, kant::BufferReader>  kantAttr;
                            kantAttr.setVersion(_current->getRequestVersion());
                            kantAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            kant::JsonValueObjPtr _p = std::make_shared< kant::JsonValueObj>();
                            kant::KT_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            kant::KantOutputStream<kant::BufferWriterVector> _os;
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return kant::KANTSERVERSUCCESS;

                }
            }
            return kant::KANTSERVERNOFUNCERR;
        }
    };


}



#endif
